#:import utils kivy.utils

<MainGrid>:
    canvas.before:
        Color:
            rgb: utils.get_color_from_hex('#212946')
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        size_hint: 1, 1
        orientation: 'vertical'
        padding: 10, 10, 0, 10

        BoxLayout:
            id: zoom
            orientation: 'horizontal'
            size_hint: 1, 0.1
            padding: 10

            Button:
                text: '-'
                size_hint_x: None
                width: self.height
                on_release: root.update_zoom(self.text)

            Label:
                text: 'x'

            Button:
                text: '+'
                size_hint_x: None
                width: self.height
                on_release: root.update_zoom(self.text)

        BoxLayout:
            size_hint: 1, 0.3